### ISSUE TITLE
Any plans to release Mediawiki 1.35.3 and future LTS releases?

### ISSUE THREAD

**Issue by nxcc** [bitnami/bitnami-docker-mediawiki#100]
Hi, we are still using the Mediawiki 1.35.2 Version of the bitnami-docker-mediawiki image, but ideally would like to upgrade to 1.35.3 as this has some bug and security fixes. I wonder if 1.35.3 and future LTS Releases will be released by bitnami. At the moment there seem to be only updates tracking latest 1.36 releases.

**Comment by marcosbc** [comment]
Hi @nxcc, unfortunately it is not within our short-term plans to support a different branch of versions (other than the latest version).

However, it should be fairly simple to create your own Docker image based on `bitnami/mediawiki:latest`. To do so, replace the files inside `/opt/bitnami/mediawiki` with the ones for the specific MediaWiki version you want (i.e. `1.35.2`).

**Comment by nxcc** [comment]
Hi @marcosbc, thanks for confirming.
