### ISSUE TITLE
Can't initialize with error: Cannot persist 'images' because it does not exist

### ISSUE THREAD

**Issue by sunny-chung** [bitnami/bitnami-docker-mediawiki#101]
**Description**

I'm trying to do a fresh installation of MediaWiki. It fails at the end of installation with an error message:
> Cannot persist 'images' because it does not exist

**Steps to reproduce the issue:**

1. Create an empty MySQL database using docker image `mysql:8.0.27`
2. Create a docker container with this image (version 1.37.1) and run

**Describe the results you received:**

Log output:
```
mediawiki 18:54:37.94 
mediawiki 18:54:37.94 Welcome to the Bitnami mediawiki container
mediawiki 18:54:37.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
mediawiki 18:54:37.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues
mediawiki 18:54:37.95 
mediawiki 18:54:37.95 INFO  ==> ** Starting MediaWiki setup **
realpath: /bitnami/apache/conf: No such file or directory
mediawiki 18:54:38.06 INFO  ==> Configuring PHP options
mediawiki 18:54:38.09 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
mediawiki 18:54:38.29 INFO  ==> Configuring file permissions for MediaWiki
mediawiki 18:54:38.33 INFO  ==> Trying to connect to the database server
mediawiki 18:54:38.54 INFO  ==> Running MediaWiki install script
mediawiki 18:55:53.18 INFO  ==> Configuring MediaWiki settings
mediawiki 18:55:53.18 INFO  ==> Setting MediaWiki short URLs
mediawiki 18:55:53.31 INFO  ==> Persisting MediaWiki installation
mediawiki 18:55:53.31 ERROR ==> Cannot persist 'images' because it does not exist
```

**Describe the results you expected:**

Installation and persistence should be proceeded successfully on correct configuration inputs.

**Additional information you deem important (e.g. issue happens only occasionally):**

1. Data volume is a host volume with owner set to user `1001` and permission `0777`. It has been checked that the container user has enough privileges to create file or directories at `/bitnami/mediawiki`.
2. (Only) `LocalSettings.php` was persisted.

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.13
 Git commit:        b455053
 Built:             Thu Aug 19 07:13:24 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.13
  Git commit:       a3bc36f
  Built:            Thu Aug 19 07:11:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00
```

- Output of `docker info`:

```
irrelevant
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.5, build 324b023a
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

N/A

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-mediawiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
