### ISSUE TITLE
connection to ldap server ( active directory ) 

### ISSUE THREAD

**Issue by MohammadrezaMasoumi** [bitnami/bitnami-docker-mediawiki#104]
### Name and Version

bitnami/mediawiki:1.37.1

### What is the problem this feature will solve?

hello 
i want to know is it possible to add connection to ldap server feature or no ? 
thanks alot

### What is the feature you are proposing to solve the problem?

for handling existing users that have domain user .

### What alternatives have you considered?

?!

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-mediawiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
