### ISSUE TITLE
"syntaxhighlight" extension not working

### ISSUE THREAD

**Issue by cyberpd** [bitnami/bitnami-docker-mediawiki#105]
### Name and Version

bitnami/mediawiki:1.37.2-0

### Environment
- WSL2 on Windows 11 21H2(22000.593), Ubuntu
- Docker 20.10.14

### Step

1. Load extensioins ( LocalSettings.php )
```
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
```

2. create wiki page
```
‎<syntaxhighlight lang="python" line>
def quick_sort(arr):
	less = []
	pivot_list = []
	more = []
	if len(arr) <= 1:
		return arr
	else:
		pass
‎</syntaxhighlight>
```

### expected
<img width="176" alt="quick_sort_python" src="https://user-images.githubusercontent.com/25042914/161871530-044e900e-9e85-42e7-8792-6d21f51f3973.png">

### error
<img width="179" alt="quick_sort_python_error" src="https://user-images.githubusercontent.com/25042914/161871586-21df647b-fdd1-4cb4-9fca-098abaf35935.png">

```
root@server:/srv/docker/mediawiki# docker compose exec mediawiki /opt/bitnami/mediawiki/extensions/SyntaxHighlight_GeSHi/pygments/pygmentize
/usr/bin/env: 'python3': No such file or directory
```

### Environment

- WSL2 on Windows 11 21H2(22000.593), Ubuntu
- Docker

```
Client: Docker Engine - Community

 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:02 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-mediawiki#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by cyberpd** [comment]
pygmentize can't execute
<code>/usr/bin/env: 'python3': No such file or directory</code>
