### ISSUE TITLE
Bump docker to release 1.28.0

### ISSUE THREAD

**Issue by andrewhowdencom** [bitnami/bitnami-docker-mediawiki#23]
Heyaa; 

Mediawiki 1.28.0 was released about a short while ago. Is it possible to bump this container to that release?

Ref: https://github.com/wikimedia/mediawiki/releases/tag/1.28.0

Cheers!

**Comment by carrodher** [comment]
Hi @andrewhowdencom,

Thanks for the notice.
We are working on the upgrade, it will be available soon.

Best regards,
Carlos Rodríguez Hernández

**Comment by andrewhowdencom** [comment]
Closed by https://github.com/bitnami/bitnami-docker-mediawiki/pull/30
