### ISSUE TITLE
enviroment variables for mariadb database name, mediawiki LocalSettings.php settings and possibly a mysqldump file to load pages

### ISSUE THREAD

**Issue by abarik1981** [bitnami/bitnami-docker-mediawiki#29]
Thanks for this, I am able to run my mediawiki. however, I would like to know how can i change the database's name (defaults to bitnami_mediawiki).

Also is there a way to provide enviroment variable for some settings in LocalSettings.php for mediawiki?

Also, it would really help if we can provide a mysqldump file that will get loaded to the database.

right now, all of these, i have to do it manually, by docker exec -it <dockername>

**Comment by sameersbn** [comment]
@abarik1981 The image requires the user to specify the database admin account defailt which is used to create a database and user for the mediawiki application. Currently it does not provide the user options to specify a custom user and database for the mediawiki application. We are currently working on this feature as it is most widely requested from our users.

With respect to configuring parameters in the `LocalSettings.php`, the file is available in the volume mounted at the `/bitnami/mediawiki` path of the container. The user is expected to modify the file to fine tune the application to their needs. After modifying the file please ensure that the container is restarted for the changes to take effect.

**Comment by ritazh** [comment]
+1

Would be great if there's a way to provide an environment variable for the database name. @prydonius would you be able to help with this? Thank you 😄 

cc @sozercan @krancour @arschles

**Comment by juan131** [comment]
Hi @ritazh 

This is only supported on WordPress at this moment. 

We have had similar requests on other Docker Images. See:

https://github.com/bitnami/bitnami-docker-testlink/issues/55
https://github.com/bitnami/bitnami-docker-phpbb/issues/49

@tompizmor @sameersbn I think we should try to give this more priority.

**Comment by ritazh** [comment]
Thanks @juan131 yes this is the same issue across all these images, including bitnami/bitnami-docker-ghost as well. 

cc @julienstroheker

**Comment by juan131** [comment]
Hi everybody 

A new revision of the Docker Image (1.29.2-r1) hast just been released and now the Bitnami Docker Mediawiki Image supports using an existing database.

More info at: https://github.com/bitnami/bitnami-docker-mediawiki#use-an-existing-database

Please feel free to use this new image and give us any feedback about this new feature.

**Comment by prydonius** [comment]
Closing since this is implemented. @abarik1981 @ritazh let us know if you have any issues with this feature!
