### ISSUE TITLE
Migrate from AWS bitnami mediawiki

### ISSUE THREAD

**Issue by edgarmove** [bitnami/bitnami-docker-mediawiki#55]
Hi, I am moving my bitnami mediawik installation from AWS to docker.
Do you have a procedure / how to for this task?

Thanks!
    EM

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
I just created this PR https://github.com/juan131/bitnami-docker-mediawiki/pull/1 adding a section to the README.md file describing the whole process.

**Comment by juan131** [comment]
@edgarmove we just merged the section describing the Migration process. Could you please try to follow it and let us know if that helps you?

**Comment by edgarmove** [comment]
Thanks! I have a deadline this week to migrate the site. I will try your procedure and report back here.
