### ISSUE TITLE
Feature Request: Log to stdout

### ISSUE THREAD

**Issue by andrewhowdencom** [bitnami/bitnami-docker-mediawiki#60]
**Description**

**Steps to reproduce the issue:**

1. Go looking for logs

**Describe the results you received:**

1. See they're not accessible with docker log

1. See apache logs. Also, maybe, mediawiki logs.

So, basically it'd be cool to see apache logs rather than "welcome to bitnami" when tailing the logs. Makes collection and aggregation easier

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. This is something we want to implement in our containers. The idea will be to redirect the logs to stdout but not to store the logs in the container itself (as it is a bad practice). We will let you know when this is implemented.

**Comment by andrewhowdencom** [comment]
If I might be so bold as to suggest, you might be able to run an init process (such as tini) and just redirect it to it's stdout/stderr (`/proc/1/fd/1`, `/proc/1/fd/2`)

**Comment by marcosbc** [comment]
Hi, in `20180422.4.0-debian-10-r0` we changed the implementation of the container and now the logs are printed via stdout/stderr, thanks to changes to the Apache initialization logic. I'm closing this, but feel free to re-open if you consider this is still an issue.
