### ISSUE TITLE
libphp5

### ISSUE THREAD

**Issue by andrewhowdencom** [bitnami/bitnami-docker-mediawiki#61]
Logs show 

```
Welcome to the Bitnami mediawiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mediawiki
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at wiki-mariadb:3306
mysql-c INFO  MySQL server listening and working at wiki-mariadb:3306
mediawi INFO 
mediawi INFO  ########################################################################
mediawi INFO   Installation parameters for mediawiki:
mediawi INFO     Persisted data and properties have been restored.
mediawi INFO     Any input specified will not take effect.
mediawi INFO   (Passwords are not shown for security reasons)
mediawi INFO  ########################################################################
mediawi INFO 
nami    INFO  mediawiki successfully initialized
INFO  ==> Starting mediawiki... 
nami    ERROR Unable to start com.bitnami.apache: httpd: Syntax error on line 155 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: /opt/bitnami/apache/modules/libphp5.so: cannot open shared object file: No such file or directory
```

**Steps to reproduce the issue:**

```
-image: bitnami/mediawiki:1.29.0-r0
+image: bitnami/mediawiki:1.29.1-r0
```

**Describe the results you received:**

My phone got very excited as uptime probes freaked out

**Describe the results you expected:**

I would continue drinking coffee and look busy

**Additional information you deem important (e.g. issue happens only occasionally):**

It's the helm chart

I think that file is on a stateful partition. I'm going to manually migrate it, but I think it's worth doing this

**Comment by andrewhowdencom** [comment]
This is probably a problem with the chart? I'm not sure the container is supposed to support mounted configuration

**Comment by jotadrilo** [comment]
Hi @andrewhowdencom,

Thanks for reporting this issue. We will force libphp to be updated at runtime.

Currently, the libphp module required by Apache is in the image `/opt/bitnami/apache/conf/httpd.conf` file. When you are reusing existing data, that file is overwritten with that data. The `httpd.conf` file that your data contains was likely generated when the required libphp module version was 5 but the image ships php and libphp 7 now.

In order to solve this issue, we will update the image revision so this is automatically done. In the meantime, you could edit the `httpd.conf` manually and replace:

```
LoadModule php5_module modules/libphp5.so
```
with
```
LoadModule php7_module modules/libphp7.so
```

or run:

```
sed -i.back 's#LoadModule php5_module.*#LoadModule php7_module modules/libphp7.so#g' /bitnami/apache/conf/httpd.conf
```

You should see only one difference:
```
diff /bitnami/apache/conf/httpd.conf /bitnami/apache/conf/httpd.conf.back
157c157
< LoadModule php7_module modules/libphp7.so
---
> LoadModule php5_module modules/libphp5.so
```

I hope this helps!

**Comment by andrewhowdencom** [comment]
This is exactly what I did ^^ in k8s it's a bit tricky as if you fuck it up you're in a reboot loop, but it was fine.

**Comment by jotadrilo** [comment]
I'm glad you finally solved the issue!
