### ISSUE TITLE
Cannot set LOC_CTYPE to default locale error in postInstallation

### ISSUE THREAD

**Issue by kelvSYC** [bitnami/bitnami-docker-mediawiki#63]
**Description**
I am trying to use docker-compose and this image to create an instance on my NAS.  The error logs show the following error:

    mediawiki_1  | nami    INFO  Initializing mediawiki
    mediawiki_1  | mysql-c INFO  Trying to connect to MySQL server
    mediawiki_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
    mediawiki_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
    mediawiki_1  | Error executing 'postInstallation': /usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
    mediawiki_1  | 

I suspect that this may be an environment issue, but any help would be useful.

**Steps to reproduce the issue:**

Simple `docker-compose up -d`, as stated in the instructions.

**Describe the results you received:**

Upon receiving the error described above, the MediaWiki container abruptly terminates; the MariaDB container is unaffected.

**Describe the results you expected:**

I expected that the container to start up normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.8
 Git commit:   5be46ee-synology
 Built:        Fri May 12 16:36:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.8
 Git commit:   5be46ee-synology
 Built:        Fri May 12 16:36:47 2017
 OS/Arch:      linux/amd64
```

- Output of `docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.11.2
Storage Driver: btrfs
Logging Driver: db
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.15+
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.704 GiB
Name: <redacted>
ID: 6VUV:QHYW:HH6C:LSGF:OLXT:2VOX:IALO:OD23:UZW7:OIZ2:5ZIH:BGRN
Docker Root Dir: /volume1/@docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is being done with the Docker app on a Synology NAS, for which the software is considered up-to-date and the hardware considered new.  docker-compose is being run through ssh, as the NAS user interface does not have a GUI accommodating docker-compose.

**Comment by juan131** [comment]
I was unable to reproduce the issue on a Debian OS neither on OS-X. Apparently there's a known issue on the Synology NAS and the modified docker distribution that they use with UTF-8. Please find out the link below:

http://forum.minimserver.com/showthread.php?tid=1710

Could you please reset the NAS or contact the Synology Support?

**Comment by yangboz** [comment]
For sure , miniDeb removed locales package , and bitnami mediawiki based on it. I made another docker tag: smartkit/mediawiki:locale to fix it up. 
And related pull request: https://github.com/bitnami/bitnami-docker-mediawiki/pull/67

**Comment by juan131** [comment]
Hi @yangboz 

Thanks for the contribution. I added some comments on your PR
