### ISSUE TITLE
Please add 'imagemagick' package so that '/usr/bin/convert' is present.

### ISSUE THREAD

**Issue by PaulSchulz** [bitnami/bitnami-docker-mediawiki#65]
The first thing I need to to do with the bitnami mediawiki image is to turn on image uploads.
I can't just do this without also adding the 'imagemagick' package, which supplies the /usr/bin/convert binary.

**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
@tompizmor @jotadrilo this component (ImageMagick) is already included on Discourse or Redmine images. What do you think about adding it to Mediawiki? Do you see any reason why not to add it?

**Comment by tompizmor** [comment]
Yes, I think we should add it to the MediaWiki docker image

**Comment by juan131** [comment]
Perfect! I'll create an internal task to add it. @PaulSchulz thanks so much for reporting it! We'll keep you updated!

**Comment by jotadrilo** [comment]
I don't see any reason not to do it :)
Thanks for noticing this @PaulSchulz!

@juan131 could you also make sure that the internal ticket to add `imagemagick` package also states tests creation to verify its integration with MediaWiki?

**Comment by juan131** [comment]
All right @jotadrilo !

**Comment by tompizmor** [comment]
Hi @PaulSchulz,

Could you please share with us the steps to reproduce the error that you experienced when imagemagick is not installed? 

I can upload images directly after start the container without changing anything in the configuration or install imagemagick.

Thanks,
Tomas

**Comment by PaulSchulz** [comment]
@tompizer By default, the image does not a have file uploads enabled in 'LocalSettings.php'. If I enable file uploads, I also need to allow /usr/bin/convert..

I would like:
1. File/image uploads to be enabled.
2. (1. then requires) the imagemagick package installed - otherwise an error is displayed when uploading files, and no thumbprints are displayed.

**Comment by tompizmor** [comment]
@PaulSchulz file uploads should be enabled by default. Can you check what image do you have? 

You can check the specific image by running this command inside the mediawiki container:

```
$ env | grep BITNAMI_IMAGE_VERSION
```

I am testing the the latest MediaWiki image (`1.29.2-r1`) and file uploads are enabled by default:

```
$ cat /opt/bitnami/mediawiki/LocalSettings.php | grep wgEnableUploads
$wgEnableUploads = true;
```

Also according to the [mediawiki documentation](https://www.mediawiki.org/wiki/Manual:Image_administration#Image_thumbnailing), ImageMagick or GD should be installed to create thumbnails. GD is already included in the PHP version shipped in the image so it seems ImageMagick is not strictly necessary.

The reason to not include imagemagick by default is to not increase the image size.

**Comment by tompizmor** [comment]
We have documented how to build a custom image including imagemagick [here](https://github.com/bitnami/bitnami-docker-mediawiki/blob/master/README.md#how-to-install-imagemagick-in-the-bitnami-mediawiki-docker-image)

**Comment by kachkaev** [comment]
How about adding imagemagick to the image by default?

**Comment by juan131** [comment]
Hi @kachkaev 

We finally discarded including the component by default in the image, and document the process instead. 

There are two main reasons for not including it by default:

- Image size
- Reduce the number of components in the image (the less components you have, the less likely to be affected by a CVE)
