### ISSUE TITLE
Extract env vars from LocalSettings.php

### ISSUE THREAD

**Issue by Morriz** [bitnami/bitnami-docker-mediawiki#72]
It is very poor design to have configuration in files like LocalSettings.php, and they should be read with something like get_env() or whatever php function is used for plucking env vars. This makes it hard to build stateless docker images.

Is there an effort to pick this up? I can do it but won't have time for a while...

**Comment by jotamartos** [comment]
Hi @Morriz,

Thank you for using our container solution. I understand you are talking about specific configuration parameters inside the LocalSettings.php file, right? 

Please note that Bitnami packages and configures already existing applications. We do not change the code of the application or how it's configured. If you have any questions or suggestions about that, we suggest you post it in the official support forums of the application. The developers can evaluate your request and provide more information to you. 

Thanks

**Comment by Morriz** [comment]
Tnx. I will take it there ;)
