### ISSUE TITLE
Can't connect to external mysql db that requires ssl

### ISSUE THREAD

**Issue by De1taE1even** [bitnami/bitnami-docker-mediawiki#73]
**Description**

I'm trying to set up a mediawiki within our kubernetes cluster that connects to our Azure mysql instance that requires ssl.  Nothing that I can find in any documentation shows me how to do this.
I tried hacking `$wgDBssl = true;` into the `/opt/bitnami/mediawiki/extensions/MultimediaViewer/tests/browser/LocalSettings.php` file
I tried modifying the sql connection in the post_init.sh file to include the `--ssl=TRUE` flag

Seems to me like there should be an easier way to do this.  Connecting to a mysql db using ssl is a very popular (and often required) practice.

**Steps to reproduce the issue:**

1. Try to connect to a database that requires an ssl connection

**Describe the results you received:**
From the log output:
```
Welcome to the Bitnami mediawiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing mediawiki
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mydb.mysql.database.azure.com:3306
mysql-c ERROR [canConnect] Connection with 'mediawiki@mydb' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'mediawiki@mydb' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'mediawiki@mydb' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'mediawiki@mydb' user is unsuccessful
mysql-c ERROR [canConnect] Connection with 'mediawiki@mydb' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error: 
 ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.
```

**Describe the results you expected:**

If I could figure out how to enable ssl to the db, I would expect a successful connection.

**Comment by javsalgar** [comment]
Hi,

Allowing SSL databases is something that we are adding little by little to our solutions. For example, we have it in applications like WordPress. I will open a task for investigating this. Though I cannot give a rough ETA, I will update the ticket when we have more information. Thank you very much for reporting.

**Comment by De1taE1even** [comment]
Is there anything I can do in the mean time to get me by?  I'm perfectly happy getting into the image and making some not-so-obvious changes to get me going in the mean time.

**Comment by javsalgar** [comment]
Hi,

The configuration scripts are written in Node.js. You can check them in `/root/.nami/components/com.bitnami.mediawiki/`. The main.js file is where you can edit the logic. If you want to use WordPress as an example, then check the `/root/.nami/components/com.bitnami.wordpress/` folder in the bitnami/wordpress container.

**Comment by De1taE1even** [comment]
Fantastic, I'll look into it, thank you.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-mediawiki#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
