### ISSUE TITLE
Feature Request: Add support for postgresql.

### ISSUE THREAD

**Issue by OrwillT** [bitnami/bitnami-docker-mediawiki#74]
Add support for Postgresql.

**Comment by rafariossaa** [comment]
Hi @OrwillT ,
  I am sorry to say that it is not currently in our priorities, but if you send a PR we will be happy to review and include it.

**Comment by rcsilva83** [comment]
Hi!

I'm interested on trying to develop this support to send a PR. I've never worked on Bitnami Docker images before but, by looking at the Dockerfile, I guess the support is just a matter of adding a `bitnami-pkg unpack` to pgsql client, right?

Where can I find the correct package name and it's hash?

Regards!

**Comment by rafariossaa** [comment]
Hi @rcsilva83 ,
  Yes, you can add a pgsql client that way. You can get them from other of our containers that use it, form example [pgpool](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/4/debian-10/Dockerfile). 
  Have into account that this will change over the time, but don't worry about that. Once integrated your changes, those will be generated by our pipeline. So, you can use a version and PR the changes needed in mediawiki.

**Comment by rcsilva83** [comment]
Hello @rafariossaa !
I started to work on this but I'm getting HTTP 404 when I try to install postgresql-client:

https://github.com/rcsilva83/bitnami-docker-mediawiki/runs/506313964?check_suite_focus=true#step:4:618

I'm following the example in pgpool... Do you know what am I doing wrong?

**Comment by rafariossaa** [comment]
Could you share your Dockerfile so far ?

**Comment by rcsilva83** [comment]
Sure: https://github.com/rcsilva83/bitnami-docker-mediawiki/blob/master/1/debian-10/Dockerfile

I added the line 14 and "/opt/bitnami/postgresql/bin:" on line 4.

**Comment by rafariossaa** [comment]
Hi, 
  I use this for the 14 line:
```
RUN bitnami-pkg unpack postgresql-client-10.12.0-1 --checksum 987971cbe05104f59132ad308e25019dc6a34cda9139e0d515e2f71de1508bd5
```
 Could you give it a try ?

**Comment by rcsilva83** [comment]
Yes, it worked! Thank you very much!

Next step is to set the correct environment variables for the database connection. Today we have MARIADB_* and MEDIAWIKI_DATABASE_* variables. I couldn't find them on this repository, so I believe they are defined on the `mediawiki` Bitnami package, right? How can I search for PostgreSQL related variables?

**Comment by rafariossaa** [comment]
Sorry, I didn't realize until  now that this container use nami, that is a javascript script that does the initialization process, so this is going to be a complex process. 
Those scripts are in the `/root/.nami/components/com.bitnami.mediawiki` folder, mainly `main.js` and `helper.js`. These scripts plus the program files, that are in `/opt/bitnami/xxxxx` is what is in the package files installed with `bitnami-pkg`

The environment variables are mapped to javascript variables in the `.json` files of the rootfs folder. 
You can see MARIADB_* and MEDIAWIKI_* environment vars mapped there. 
You can find the postgres-client variables in the `nami.json` in the `com.bitnami.postgres-client` folder, then you can create a mapping between the env vars you want to the postgres-client javascript vars.

Hope this helps.
