### ISSUE TITLE
mysql did not finishes starting

### ISSUE THREAD

**Issue by crissato** [bitnami/bitnami-docker-mediawiki#75]
docker --version
Docker version 19.03.6, build 369ce74a3c

docker-compose --version
docker-compose version 1.23.1, build b02f1306

uses de docker-compose.yml
it starts mediawiki but mysql stops

CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                          PORTS                                         NAMES
fbf19d9ba9be        bitnami/mediawiki:1    "/app-entrypoint.sh …"   About a minute ago   Up About a minute               0.0.0.0:8081->80/tcp, 0.0.0.0:8443->443/tcp   mediawiki_mediawiki_1_44f6538ccfb0
d81153188f07        bitnami/mariadb:10.3   "/entrypoint.sh /run…"   About a minute ago   Exited (1) About a minute ago                                                 mediawiki_mariadb_1_7b91b0a7cb7e

mediawiki]$ docker logs mediawiki_mariadb_1_7b91b0a7cb7e
 14:57:47.33
 14:57:47.33 Welcome to the Bitnami mariadb container
 14:57:47.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
 14:57:47.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
 14:57:47.33 Send us your feedback at containers@bitnami.com
 14:57:47.33
 14:57:47.34 INFO  ==> ** Starting MariaDB setup **
 14:57:47.38 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
 14:57:47.39 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
 14:57:47.39 INFO  ==> Initializing mariadb database
 14:57:47.41 INFO  ==> Using persisted data
 14:57:47.42 INFO  ==> Running mysql_upgrade
 14:57:47.42 INFO  ==> Starting mariadb in background
 14:57:48.47 INFO  ==> Stopping mariadb

Welcome to the Bitnami mediawiki container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing mediawiki
mysql-c INFO  Trying to connect to MySQL server

**Comment by marcosbc** [comment]
@crissato Your error looks weird. We have a couple of questions to get more information on this issue:

- Is this happening since you deployed MediaWiki, or did it just start failing recently (after having a working image)?
- Could you share your Docker Compose file? We want to see if it's possible you're using an old release of the Bitnami MariaDB Docker image.

**Comment by marcosbc** [comment]
In addition to the above, could you try running it with the environment variable BITNAMI_DEBUG=true, this could give more information.

**Comment by crissato** [comment]
I ve restarted docker daemon and it started work again

**Comment by marcosbc** [comment]
In that case I'm closing this issue. Thanks for letting us know!
