### ISSUE TITLE
Install plugin that requires installing a composer package

### ISSUE THREAD

**Issue by rcsilva83** [bitnami/bitnami-docker-mediawiki#77]
Hi!

I'm trying to install [OpenID_Connect extension](https://www.mediawiki.org/wiki/Extension:OpenID_Connect) and it requires a composer package to be installed. Which is the recommended way to install this composer package?

Thanks for your attention.

Regards,

Rodrigo

**Comment by andresbono** [comment]
Hi @rcsilva83, `composer` is already available in the mediawiki container. You can find it under `/opt/bitnami/php/bin/composer`.

**Comment by rcsilva83** [comment]
Nice. Do you think I should build my own image based Bitnami's image and the composer package installed or should I run Docker exec commands to install it on the running container? I feel the first option is better but it would make it more difficult do update.

**Comment by andresbono** [comment]
Building your own base image from the bitnami one is what we recommend in these cases. Imagine that the container goes down for some reason. You will need to execute the docker exec command again because your required packages will be missing until then.

**Comment by rcsilva83** [comment]
OK. Thank you very much for your attention!
