### ISSUE TITLE
Only deploying Mariadb

### ISSUE THREAD

**Issue by paxinos** [bitnami/bitnami-docker-mediawiki#78]
When deploying on Rancher through their App Catalog system, only mariadb is deployed.   There is a service defined for media wiki, but that container is not deployed.

**Comment by juan131** [comment]
Hi @paxinos 

- Are you deploying Mediawiki using the [Bitnami Helm chart for Mediawiki](https://github.com/bitnami/charts/tree/master/bitnami/mediawiki) on a K8s environment?

Do you have any restriction/policy in the cluster where you're deploying the solution regarding running containers as root?

**Comment by paxinos** [comment]
Deploying on a K8S environment.  Using the Rancher catalog manager.

No restrictions that I am aware of.

The MariaDB container deploys.   There is a service for MediaWiki, but the
container does not deploy - or even a sign that it tried and failed.
Normally I would see the pod with error messages...

Pax

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by juan131** [comment]
HI @paxinos 

MariaDB is a non-root container (find more information at https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/) which is something supported in the vas majority of Kubernetes clusters. 

On the other hand, Mediawiki is not a root container. Some K8s distributions (such as Openshift or TKG) exclusively allow to run non-root containers and, therefore, will prevent containers such as Mediawiki to be scheduled in your cluster.

Please check (or ask the administrator of your cluster if you don'y have admin privileges) if you defined security policies in the cluster that prevent to run root containers. You can find more information in the link below:

- https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups

**Comment by paxinos** [comment]
So, that wasn't it at all...   Seems that the Helm Chart isn't ready for
use in the Rancher Catalog

After manually installing the Helm Chart I get the following...   after
following the instructions I now have a deployed media wiki without any
changes to the cluster...


1. Get the Mediawiki URL by running:


  NOTE: It may take a few minutes for the LoadBalancer IP to be available.

        Watch the status with: 'kubectl get svc --namespace kmfap -w
kmfap-mediawiki'


  export APP_HOST=$(kubectl get svc --namespace kmfap kmfap-mediawiki
--template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end
}}")

  export APP_PASSWORD=$(kubectl get secret --namespace kmfap
kmfap-mediawiki -o jsonpath="{.data.mediawiki-password}" | base64 --decode)

  export DATABASE_ROOT_PASSWORD=$(kubectl get secret --namespace kmfap
kmfap-mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode)

  export APP_DATABASE_PASSWORD=$(kubectl get secret --namespace kmfap
kmfap-mariadb -o jsonpath="{.data.mariadb-password}" | base64 --decode)


2. Complete your Mediawiki deployment by running:


  helm upgrade kmfap bitnami/mediawiki \

    --set
mediawikiHost=$APP_HOST,mediawikiPassword=$APP_PASSWORD,mariadb.mariadbRootPassword=$DATABASE_ROOT_PASSWORD,mariadb.db.password=$APP_DATABASE_PASSWORD


2. Get your MediaWiki login credentials by running:


    echo Username: admin

    echo Password: $(kubectl get secret --namespace kmfap kmfap-mediawiki
-o jsonpath="{.data.mediawiki-password}" | base64 --decode)


*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by juan131** [comment]
Hi @paxinos 

I am not very familiar with Rancher UI but yes, this Helm chart requires modifying some parameters to successfully deploy it (like the hostname). So I guess you need to find the way to set those parameters through the Rancher UI.
