### ISSUE TITLE
How to enable LDAP Apache modules

### ISSUE THREAD

**Issue by alesnav** [bitnami/bitnami-docker-mediawiki#79]
**Description**

I am trying to enable LDAP modules as said in [your docs pages](https://docs.bitnami.com/bch/apps/mediawiki/configuration/enable-modules/), but I am unable to get it done.

I have tested the following workarounds:

- **Using Docker Configs** to change `/opt/bitnami/apache/conf/httpd.conf`. It fails due to the following error: `Error executing 'postInstallation': EROFS: read-only file system, open '/opt/bitnami/apache/conf/httpd.conf'`

- **Changing Docker entrypoint**, forcing uncomment LDAP modules in `http.conf` file using `sed`, but it fails (don't know why).
```
#!/bin/bash
sed -i '/mod_authnz_ldap.so/s/^#*//g' /opt/bitnami/apache/conf/httpd.conf
sed -i '/mod_ldap.so/s/^#*//g' /opt/bitnami/apache/conf/httpd.conf
/bin/bash /app-entrypoint.sh
```

- **Mapping the volume** to get persistant data (`optvolume:/opt/bitnami/`), but it fails, too, as that volume is empty.

What is the recommended way to enable LDAP modules in Bitnami's Mediawiki Docker image?

Sorry, but I don't see any tutorial related to this topic.

Thanks,
Best regards

**Comment by rafariossaa** [comment]
Hi,
  Those instructions are for the MediaWiki Stack for Bitnami Cloud Hosting which is a VM.
  For the container, you should be using [this](https://github.com/bitnami/bitnami-docker-mediawiki#user-content-extend-this-image).

   Could you give it a try ?

**Comment by alesnav** [comment]
Hello @rafariossaa , thanks for your response.

I see that the only way to get it done is by customizing the Docker image then... So I'm closing the issue.

But anyway, I think that it will be "better" if the official Bitnami image allows setting this minimal configuration change using one of the options commonly used for this goal. I mean, one of the following approaches:

- Env variables
- Docker configs
- External config file to override some `httpd.conf` configurations

Thanks,
Best regards

**Comment by rafariossaa** [comment]
Hi @alesnav ,
  Thanks for the suggestion. 
  In any case we are open to PRs, so feel free to send one. We will glad to review and merge it.
