### ISSUE TITLE
Initial MediaWiki Setup Fails, Can't Find mw-config/index.php

### ISSUE THREAD

**Issue by ModestTG** [bitnami/bitnami-docker-mediawiki#80]
**Description**
As it says in the description, when I try to access a new instance of MediaWiki, setup using Docker Compose, I get a screen showing that LocalSettings.php cannot be found, and that the initial setup for the database needs to be completed. I click the link to setup my LocalSettings.php, and I get redirected to the directory mw-config/index.php, and I get a 404 error. I don't know about the apache2 file structure to see if I can find that file in the container, but I assume it's not there if I'm getting the 404. I do notice that I am seeing a LocalSettings.php in my /bitnami directory which is mounted on my host system, as well as a LocalSettings.php located in /opt/bitnami/mediawiki in the container. All notions point to LocalSettings.php being setup, but not being accessible for some reason. Any advice on what I should look for or next steps?

**Steps to reproduce the issue:**

Setup MediaWiki via Docker Compose using the following settings:

Docker-Compose
```
mediawiki:
    image: bitnami/mediawiki:latest
    container_name: MediaWiki
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - default
      - traefik_proxy
    ports:
      - "8092:80"
    volumes:
      - "/mnt/container_data/mediawiki/bitnami:/bitnami"
    env_file:
      - ./envs/mediawiki.env
```
env_file:
```
MEDIAWIKI_USERNAME=eweishaar
MEDIAWIKI_PASSWORD=[redacted]
MEDIAWIKI_EMAIL=[redacted]
MEDIAWIKI_WIKI_NAME=EW Homelab Services Wiki
MARIADB_HOST=mysql
MARIADB_PORT_NUMBER=3306
MEDIAWIKI_DATABASE_NAME=mediawiki_db
MEDIAWIKI_DATABASE_USER=eweishaar
MEDIAWIKI_DATABASE_PASSWORD=[redacted]
```
Container Log output
```
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing mediawiki
mediawi INFO  Preparing PHP environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mysql:3306
mysql-c INFO  MySQL server listening and working at mysql:3306
mediawi INFO
mediawi INFO  ########################################################################
mediawi INFO   Installation parameters for mediawiki:
mediawi INFO     Persisted data and properties have been restored.
mediawi INFO     Any input specified will not take effect.
mediawi INFO   This installation requires no credentials.
mediawi INFO  ########################################################################
mediawi INFO
nami    INFO  mediawiki successfully initialized
INFO  ==> Starting gosu...
[Tue Jun 16 23:05:21.977872 2020] [ssl:warn] [pid 88] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 16 23:05:21.978932 2020] [ssl:warn] [pid 88] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 16 23:05:22.050852 2020] [ssl:warn] [pid 88] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 16 23:05:22.051752 2020] [ssl:warn] [pid 88] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 16 23:05:22.084325 2020] [mpm_prefork:notice] [pid 88] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.3.19 configured -- resuming normal operations
[Tue Jun 16 23:05:22.084462 2020] [core:notice] [pid 88] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
10.0.0.4 - - [16/Jun/2020:23:05:31 +0000] "GET / HTTP/1.1" 200 390
10.0.0.4 - - [16/Jun/2020:23:05:42 +0000] "GET /mw-config/index.php HTTP/1.1" 404 196
10.0.0.4 - - [16/Jun/2020:23:05:54 +0000] "GET /mw-config/index.php HTTP/1.1" 404 196
10.0.0.4 - - [16/Jun/2020:23:09:23 +0000] "GET / HTTP/1.1" 200 390
10.0.0.4 - - [16/Jun/2020:23:09:29 +0000] "GET /mw-config/index.php HTTP/1.1" 404 196
10.0.0.4 - - [16/Jun/2020:23:12:18 +0000] "GET / HTTP/1.1" 200 390
10.0.0.4 - - [16/Jun/2020:23:12:19 +0000] "GET /mw-config/index.php HTTP/1.1" 404 196
10.0.0.4 - - [16/Jun/2020:23:23:24 +0000] "GET / HTTP/1.1" 200 390
10.0.0.4 - - [16/Jun/2020:23:23:28 +0000] "GET /mw-config/index.php HTTP/1.1" 404 196
```
Multiple instances of the 404 error when I try to refresh the page

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 26
  Running: 25
  Paused: 0
  Stopped: 1
 Images: 47
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-101-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 98.35GiB
 Name: esxi-docker1
 ID: CRCV:FBSX:LU65:ERSN:2ND4:AHA4:ZDZC:E3RJ:NGYL:HVTT:52TB:K2HQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker on Ubuntu VM

**Comment by juan131** [comment]
Hi @ModestTG 

> I do notice that I am seeing a LocalSettings.php in my /bitnami directory which is mounted on my host system, as well as a LocalSettings.php located in /opt/bitnami/mediawiki in the container.

This is related to the persistence. Mediawiki moves some files that must be persisted during restarts to `/bitnami/mediawiki` and then it creates symlinks from `/opt/bitnami/mediawiki/` to `/bitnami/mediawiki/`. The reason why you see these files in your filesystem is because you mounted it in the container:

```yaml
    volumes:
      - "/mnt/container_data/mediawiki/bitnami:/bitnami"
```

The problem is that you didn't give Mediawiki any hostname and Mediawiki expect to be needs that to be properly configured. Please set the environment variable `MEDIAWIKI_HOST` with some value (e.g. `mediawiki.local`) and then associate that hostname to your localhost by modifying your `/etc/hosts`:

```bash
echo "127.0.0.1 mediawiki.local" | sudo tee -a "/etc/hosts/"
```

Then if you create your Mediawiki from scratch (removing everything that was created previously at your file system `/mnt/container_data/mediawiki/bitnami`), you should be able to access Mediawiki browsing to http://mediawiki.local:8092

**Comment by ModestTG** [comment]
> The problem is that you didn't give Mediawiki any hostname and Mediawiki expect to be needs that to be properly configured. Please set the environment variable MEDIAWIKI_HOST with some value (e.g. mediawiki.local) and then associate that hostname to your localhost by modifying your /etc/hosts:

Just so I understand correctly, I need to add the EV `MEDIAWIKI_HOST` to my env file, then I need to update the **container's** `/etc/hosts` file to add a hostname to `127.0.0.1`? I assume you're referring to the mediawiki container's `/etc/hosts` file in your response. If that's the case, shouldn't I be able to just put `MEDIAWIKI_HOST=127.0.0.1` into my env file and skip updating `/etc/hosts`?

To be proactive I tried the following steps and still got failures
1. Stop mediawiki: `docker-compose stop mediawiki`
1. added the line `MEDIAWIKI_HOST=127.0.0.1` to the env file
2. Deleted old config from volume bind: `rm -rf /mnt/container_data/mediawiki/bitnami/*`
3. Restarted mediawiki: `docker-compose up -d mediawiki`

After performing these steps, I'm still experiencing the same issue.

Does `MEDIAWIKI_HOST` not work with IPs?

Let me know if I'm doing anything wrong. It's worth noting that I am installing this docker container on a local server running Ubuntu Server on a VM provided by ESXi. I am trying to access MediaWiki from a web browser on a Windows 10 workstation (completely different machine from where MediaWiki is being hosted). I figured you knew this but just thought I would make that clear. Thanks for a quick reply!

**Comment by juan131** [comment]
Hi @ModestTG 

> Just so I understand correctly, I need to add the EV MEDIAWIKI_HOST to my env file, then I need to update the container's /etc/hosts file to add a hostname to 127.0.0.1? I assume you're referring to the mediawiki container's /etc/hosts file in your response. If that's the case, shouldn't I be able to just put MEDIAWIKI_HOST=127.0.0.1 into my env file and skip updating /etc/hosts?

It's exactly the opposite. You need to edit the `/etc/hosts` in your Ubuntu VM, so your VM associates the hostname `mediawiki.local` to `127.0.0.1`. 
Then, you need to add the `MEDIAWIKI_HOST` to your environment file (the one you're using in the lines below) with the value: `MEDIAWIKI_HOST=mediawiki.local`

```
    env_file:
      - ./envs/mediawiki.env
```

This way Mediawiki thinks it needs to create the links using `mediawiki.local`, and your VM is able to translate `mediawiki.local` to `127.0.0.1`, so you can access your site opening a browser in the Ubuntu VM and browsing to http://mediawiki.local:8092

**Comment by ModestTG** [comment]
Thanks for the reply @juan131 

> I am trying to access MediaWiki from a web browser on a Windows 10 workstation (completely different machine from where MediaWiki is being hosted).

In my last response I noted that I am trying to access MediaWiki from a Windows 10 Workstation.

> It's worth noting that I am installing this docker container on a local server running Ubuntu Server

The machine hosting MediaWiki is running Ubuntu _Server_ 18.04, so I don't have a GUI/browser that I can use to access MediaWiki locally on the VM.

I have many other web based services running in containers on this Ubuntu Server VM, and typically what I would do is access them by supplying the IP of the Ubuntu VM with the port. For example, this ubuntu VM is running on my internal network at IP `10.0.0.126`, so I've been trying to access MediaWiki by typing in `http://10.0.0.126:8092` into my browser, and this is where I'm seeing the failures occur.

I updated my `/etc/hosts` file on my Ubuntu Server VM, and updated `MEDIAWIKI_HOST` in my `env` file, and I'm still getting the same failure.

Is it not possible to access MediaWiki from another machine other than where the machine is being hosted? I can't imagine that's the case, but you have suggested that I need to access it from my VM, which I cannot due because of the lack of any display features. Let me know if you need any other information.

-ModestTG

**Comment by juan131** [comment]
Hi @ModestTG 

> The machine hosting MediaWiki is running Ubuntu Server 18.04, so I don't have a GUI/browser that I can use to access MediaWiki locally on the VM.

In that case, you can still access Mediawiki, but it needs to be configured properly. My recommendation is using a hostname, so I would do this:

- Configure `MEDIAWIKI_HOST=mediawiki.local` in the Mediawiki container.
- Configure you laptop (Windows 10) to associate `mediawiki.local` to the IP of your Ubuntu VM (10.0.0.126). Since it's a Windows computer, the process is a little bit different. Please follow [this tutorial ](https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/).

Once you have this, the web request will follow this process:

- You tell the browser (e.g. Chrome): Go to `http://mediawiki.local:8092` 
- Browser: "Who is `mediawiki.local`?" Windows: "According to my config, it's 10.0.0.126"
- Browse sends request to 10.0.0.126 (the VM) at port 8092
- The process listening in that port is Docker so it passes the request to Mediawiki container.
- Mediawiki generates the content and answers the request, generating content with links to `mediawil.local` which is correct since you're Windows computer is using that hostname to access it.

**Comment by ModestTG** [comment]
Hi @juan131,

I followed your instructions, and I still got the same result. I didn't think referencing the web server with a hostname vs an IP would make any difference but I tried it anyways per your instructions and I still got the same error.

The more I work with this error, the more I realize that the folder isn't missing (`/mw-config/index.php`), rather, it's not being created / included with the container. I assume the whole point of having the EVs is so that you don't have to go through the initial setup to create `LocalSettings.php`. The root of this issue is that `LocalSettings.php` can't be found, so I'm being redirected. When redirected, the page doesn't exist because I'm assuming in theory I shouldn't have to be redirected due to `LocalSettings.php` being created at container startup.

So, with this realization, I have looked around the filesystem on the container and found `/opt/bitnami/mediawiki/LocalSettings.php` does exist with the following entry in the filesystem:
`lrwxrwxrwx 1 root root 36 Jun 22 15:08 LocalSettings.php -> /bitnami/mediawiki/LocalSettings.php`. So it appears that this file is getting created, but when I try and access the web server, it's saying that it can't find `LocalSettings.php`. Maybe this means that I have a misconfigured `LocalSettings.php`. Looking in this file, having set my `MEDIAWIKI_HOST=mediawiki.host` environment variable per your latest suggestion, I see that `$wgServer = "//mediawiki.local";`. Not sure if `//` is supposed to be there in this variable, and I have no idea how it would get there.

Thank you for your continued support on this issue, Let me know if you need any more information.

-ModestTG

**Comment by juan131** [comment]
Hi @ModestTG 

I just tried to reproduce on my side, and it worked without any issue for me. Please note that I did everything on my Mac, but it should work exactly the same way for you.

These are the steps I followed:

- Clone this repo
- Apply the changes below in the main **docker-compose.yaml**:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 5d31e0c..a3440f0 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -16,6 +16,7 @@ services:
       - MEDIAWIKI_DATABASE_USER=bn_mediawiki
       - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
       - ALLOW_EMPTY_PASSWORD=yes
+      - MEDIAWIKI_HOST=mediawiki.local
     ports:
       - '80:80'
       - '443:443'
```

- Edit **/etc/hosts** file:

```console
$ echo "127.0.0.1 mediawiki.local" | sudo tee -a /etc/hosts
127.0.0.1 mediawiki.local
```

- Start the container (previously I ensure there was no existing data from previous deployments):

```console
$ docker-compose down -v
$ docker-compose up -d
```

- Wait until Mediawiki is ready:

```console
$ docker-compose logs mediawiki
...
mediawiki_1  | mediawi INFO
mediawiki_1  | nami    INFO  mediawiki successfully initialized
mediawiki_1  | INFO  ==> Starting gosu...
...
```

- Open a browser and navigate to http://mediawiki.local

![Screenshot 2020-06-24 at 08 33 30](https://user-images.githubusercontent.com/6740773/85509268-f75e7880-b5f5-11ea-851c-04cbea9cfcc8.png)

**Comment by ModestTG** [comment]
Hi @juan131,

Thanks again for the reply. I can't help but notice in your example of a working MediaWiki instance that you didn't actually link the DB to either MariaDB or MySQL. From the Readme.MD it says:

> MediaWiki is an extremely powerful, scalable software and a feature-rich wiki implementation that uses PHP to process and display data stored in a database, such as MySQL.

Right in the description, you are told to use a DB backend, yet in your example `docker_compose.yml` file, you don't have any of the EV's required to link MediaWiki to a DB. Your logs even show that you didn't initialize a DB, because no link was made. 

From the Readme.MD:

>If you remove the container all your data and configurations will be lost, and the next time you run the image the database will be reinitialized. To avoid this loss of data, you should mount a volume that will persist even after the container is removed. For persistence you should mount a volume at the /bitnami path. Additionally you should mount a volume for persistence of the MariaDB data. 

Bitnami even has an image for MariaDB, and the quote has a link on how to setup MariaDB. Using the DB backend ensures that my information persists on container restart, and yet in your configuration you have not configured a DB backend at all!

In your test, if you start to make changes, then restart the container, will those changes persist? They shouldn't based on the way container's work. Your `LocalSettings.php` might get saved if you have `/bitnami` mounted to the local filesystem, but any page edits that get saved in the DB will not be present.

In a production environment, this is unacceptable practice. The test you performed is not an accurate representation as to how MediaWiki is both deployed and used both at the hobbyist level and at the professional production level. This software is meant to be deployed on a headless server, and accessed over the network from another workstation. That is all I am trying to accomplish.

For some reason, my `LocalSettings.php` is not being found, and I'm getting redirected to a directory that is empty. This is the root of my issue. I have my config posted at the top of this issue, and from what I can tell it should be correct. Yet, my LocalSettings.php is not being found. This very well could be a permissions issue in the mounted filesystem, in which case I'll have to do more digging. Thanks for all of your responses up to this point. Let me know if you have any more advice.

**Comment by juan131** [comment]
Hi @ModestTG 

I am using a MariaDB database. Please take a look to the **docker-compose.yaml** I'm using: https://github.com/bitnami/bitnami-docker-mediawiki/blob/master/docker-compose.yml

As you can see, that Docker Compose is creating two containers: a Mediawiki container and a MariaDB container. Mediawiki is configured to used that MariaDB container as the database backend (see `MARIADB_HOST=mariadb`)

I agree this is just an example and it's not valid for production environments, but I just wanted to show you how to configure Mediawiki so you can access it using a hostname.
