### ISSUE TITLE
Restricted content when trying to enter the website

### ISSUE THREAD

**Issue by mr-bat** [bitnami/bitnami-docker-mediawiki#82]
**Description**
```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-mediawiki/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```
After running these two commands and trying to enter my wiki for the first time it shows me dialog prompt asking me for my username and password claiming the content is restricted.

**Steps to reproduce the issue:**

1. run the above commands
2. try to enter the website

**Describe the results you received:**
I received the following prompt:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/16259723/91702075-0ea56f00-eb2d-11ea-8878-90bedb31c11e.png">

**Describe the results you expected:**
To properly enter the website

**Comment by javsalgar** [comment]
Hi,

I was unable to reproduce the issue in neither Chrome or Firefox

![image](https://user-images.githubusercontent.com/1133777/91714045-34f9f780-eb8b-11ea-8426-39171c11d8b1.png)

Which browser version are you using? Are going to a specific page?

**Comment by mr-bat** [comment]
I am using Firefox. No, I just entered the IP address of my server and was waiting for the homepage of the wiki.

**Comment by javsalgar** [comment]
Just to confirm, don't you have any other application running that could be conflicting? Does the issue happen when entering the container and executing curl?
