### ISSUE TITLE
Cannot install AWS extension using composer

### ISSUE THREAD

**Issue by Jyosua** [bitnami/bitnami-docker-mediawiki#85]
I'm using the latest version of this docker container that is publicly released. Git was missing from the container, so I cloned outside of it and copied the files to the /bitnami/mediawiki/extensions/AWS folder. Then I did a docker exec to shell into the container and try to run `composer install`.

I received the following errors when I attempted this:
```
I have no name!@a80f1dec16d2:/bitnami/mediawiki/extensions/AWS$ composer install
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 39 installs, 0 updates, 0 removals

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///opt/bitnami/php/bin/composer.phar/vendor/symfony/console/Application.php on line 952

Warning: proc_open(): fork failed - Cannot allocate memory in phar:///opt/bitnami/php/bin/composer.phar/vendor/symfony/console/Application.php on line 952

  [RuntimeException]
  /bitnami/mediawiki/extensions/AWS/vendor does not exist and could not be created.
```

Do you have a solution for this? It doesn't look like I have access to sudo, so I can't fiddle with any permissions...

**Comment by Jyosua** [comment]
So after poking around a little bit more, it appears that in order to get this to work, on the host system you need to do:
`sudo chown -R 1001:root AWS`
 Then put the AWS folder in another folder, like `test` for instance. Then do:
```
cd test
docker cp ./. container-name:/bitnami/mediawiki/extensions/
```
That will ensure the AWS folder has the proper permissions once inside the container. Then you can do `composer install` and it will work.

**Comment by carrodher** [comment]
The MediaWiki container is following a [non-root approach](https://docs.bitnami.com/tutorials/work-with-non-root-containers) since [version 1.34.2-debian-10-r5](https://github.com/bitnami/bitnami-docker-mediawiki#1342-debian-10-r5). That means the user executing the container and the process (as well as the owner of the directories) is a non-privileged user, so as you rightly did, users need to give the proper permission to that folder (or execute the container as a privileged user)

**Comment by Jyosua** [comment]
Could you perhaps add instructions for this to the readme? I feel like installing extensions that use composer is a common usecase and the bit about permissions is a tiny, tiny footnote that isn't clear about the group and is really easy to miss.

**Comment by carrodher** [comment]
There are some instructions in the ["Customize this image"](https://github.com/bitnami/bitnami-docker-mediawiki#extend-this-image) section about how to extend the Docker image. In the example, the user is modified in the Dockerfile to install `vim`, it is set to root and then 1001 again. Do you think it would be useful to add something related to your use case in that section? Do you like to send a PR? Thanks
