### ISSUE TITLE
Error "No such file or directory ... Maintenance.php"

### ISSUE THREAD

**Issue by leanhdung1994** [bitnami/bitnami-docker-mediawiki#90]
I've found a bug of Parsoid from MediaWiki and informed it to people at MediaWiki. They have fixed it. The detail is at https://phabricator.wikimedia.org/T280246. I hope that you can update Bitnami MediaWiki with this fix. Parsoid is the essential tool in my process of parsing Wikipedia xml dump to html.

Thank you so much for your help!

Best regards,

Dung Le.

**Comment by Mauraza** [comment]
Hi @leanhdung1994,

I'm going to create an internal task to investigate, but if an upstream issue of Medikiwi we have to wait until they solve it.
